name: GitHub-Profile-Snake

on:
  schedule:
    - cron: "0 0 * * *" # Runs once a day at midnight (UTC)
  workflow_dispatch: # Allows manual triggering from the Actions tab

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Platane/snk@master
        id: snake-gif
        - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: Roberlanderrsilva
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
